### PR TITLE
Add note to README saying no active maintenance

### PR DESCRIPTION
**Pull request by dgmstuart**
We want to be explicit about the status of the project.

### CODE REVIEW

**Comment by dgmstuart** [comment]
@Burgestrand Maybe it's as simple as this? We could additionally say "we think this is feature complete" etc. but I'm not sure if that's valuable, and it's nice to be able to have a template text which we can copy-paste to other projects.

**Review by Burgestrand — APPROVED** [review]
I like the way you've managed to frame this. Well put!

* As a potential user it tells me everything I need to know about the state of things right now.
* As a maintainer it gives us flexibility, say if we were to ever use it again.

**Comment by Burgestrand** [comment]
> We could additionally say "we think this is feature complete" etc. but I'm not sure if that's valuable

@dgmstuart I believe it would be, but the truth is we don't know if that's true, so we better not.

**Comment by dgmstuart** [comment]
Cool - I mostly just wrote what I remember you saying 😄. Let's use this as a template for other services. I'll add it to the project board.

**Pull request merged**
